src/main/java/com/glitchcube/ServletContextBean.java
package com.glitchcube;

import javax.ejb.Stateless;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.ServletContext;

/**
 * @author: glitchcube.com
 */
@Stateless //https://docs.oracle.com/javaee/7/tutorial/ejb-intro002.htm#GIPIN
@Named //Point 6.3.1.4 https://docs.oracle.com/javaee/7/tutorial/webapp003.htm#GLQLK
public class ServletContextBean {

    @Inject
    private ServletContext context;

    public String getServerInfo() {
        return context.getServerInfo();
    }

    public String getJsfVersion() {
        return FacesContext.class.getPackage().getImplementationVersion();
    }
}

src/main/java/com/glitchcube/SimpleFormBean.java
package com.glitchcube;

import javax.enterprise.inject.Model;
import javax.validation.constraints.*;

/**
 * @author: glitchcube.com
 */
//Configure managed beans: https://docs.oracle.com/javaee/7/tutorial/jsf-configure001.htm#GIRCH
@Model //shorthand for @Named @javax.enterprise.context.RequestScoped
public class SimpleFormBean {

    //Bean validation: https://docs.oracle.com/javaee/7/tutorial/partbeanvalidation.htm#sthref1322
    @NotNull
    @Pattern(regexp = "[æøåÆØÅA-Za-z]*")
    private String name;

    private String land;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLand() {
        return land;
    }

    public void setLand(String land) {
        this.land = land;
    }
}

src/main/webapp/pages/info.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition template="template/frame-template.xhtml">
    <ui:define name="content">
        This page contains only minimum for creating a page from the template.

        <br/>
        Service info: #{servletContextBean.serverInfo}
        <br/>
        Jsf version: #{servletContextBean.jsfVersion}
    </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/response.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"> <!-- https://docs.oracle.com/javaee/7/tutorial/jsf-facelets009.htm -->

<h:body>
    <ui:composition template="/pages/template/frame-template.xhtml">
        <ui:define name="content">
            <h:outputText value="Welcome #{simpleFormBean.name}, from #{simpleFormBean.land}"/>
            <br/>
            <h:button p:autofocus="autofocus" value="Back" outcome="welcome"/>
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/pages/template/frame-template.xhtml
<!DOCTYPE html>
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<!-- https://docs.oracle.com/javaee/7/tutorial/jsf-facelets004.htm#GIQXP -->
<!-- http://getbootstrap.com/getting-started/#template -->
<h:head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <h:outputStylesheet library="default" name="/css/bootstrap.min.css"/>
    <title>JSF example</title>
</h:head>
<h:body>
    <div class="container">
        <nav class="navbar navbar-default">
            <ul class="nav navbar-nav">
                <li class="active"><h:link outcome="welcome">Welcome</h:link> </li>
                <li><h:link outcome="info">Info</h:link></li>
            </ul>
        </nav>

        <ui:insert name="content"/>

        <h:outputScript library="default" name="/js/jquery-3.2.1.min.js"/>
        <h:outputScript library="default" name="/js/bootstrap.min.js"/>
    </div>
</h:body>
</html>

src/main/webapp/pages/welcome.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"> <!-- https://docs.oracle.com/javaee/7/tutorial/jsf-facelets009.htm -->
<h:body>
    <ui:composition template="template/frame-template.xhtml">
        <ui:define name="content">
            <h:form>
                Name:<h:inputText id="name"
                             p:autofocus="autofocus"
                             value="#{simpleFormBean.name}"/>
                Land:<h:inputText id="age"
                             value="#{simpleFormBean.land}"/>
                <h:commandButton value="Submit" action="response"/> <!-- Implicit navigation https://docs.oracle.com/javaee/7/tutorial/jsf-intro005.htm#BNAQL -->
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>